#! /bin/sh

sxhkd -m 1 &
picom &
feh --bg-fill ~/.config/bspwm/wall &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII

bspc config border_width		0
bspc config window_gap			0

bspc config split_ratio			0
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Steam	  desktop='^12'	state=monocle
bspc rule -a Firefox  desktop='^11'
